apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/scaffolding?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && 
      ( "cmd/trillian/createtree/*".pathChanged() || ".tekton/trillian-createtree-push.yaml".pathChanged() || "Dockerfile.trillian-createtree.rh".pathChanged() || "config/rekor/createtree/*".pathChanged() || "go.mod".pathChanged() || "Makefile".pathChanged() || "trigger-konflux-builds.txt".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: scaffold
    appstudio.openshift.io/component: trillian-createtree
    pipelines.appstudio.openshift.io/type: build
  name: trillian-createtree-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile.trillian-createtree.rh
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/securesign/scaffold-trillian-createtree:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: '{"path": ".", "type": "gomod"}'
  - name: go_unit_test
    value: true
  - name: go_test_command
    value: go test $(go list ./... | grep -v 'third_party/VENDOR-LICENSE/github.com/letsencrypt/boulder/goodkey')
  - name: go_base_image
    value: brew.registry.redhat.io/rh-osbs/openshift-golang-builder@sha256:356986205e66dcc03ef9a9fef5a7a13d6d59c29efacf1d971f9224c678932cf0
  taskRunSpecs:
    - pipelineTaskName: prefetch-dependencies
      stepSpecs:
        - name: prefetch-dependencies
          computeResources:
            requests:
              cpu: '3'
              memory: 3Gi
            limits:
              cpu: '3'
              memory: 3Gi
    - pipelineTaskName: run-unit-test
      stepSpecs:
        - name: run-tests
          computeResources:
            requests:
              cpu: '3'
              memory: 3Gi
            limits:
              cpu: '3'
              memory: 3Gi
      serviceAccountName: appstudio-pipeline
      podTemplate:
        imagePullSecrets:
        - name: brew-registry-pull-secret
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: 'https://github.com/securesign/pipelines.git'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: 'pipelines/docker-build-oci-ta.yaml'
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
